# ----------------------------------------------------- #
# A Snakemake workflow for nanopore basecalling         #
# and multiplexing using dorado.                        #
#                                                       #
# Authors: Rina Ahmed-Begrich                           #
# License: MIT                                          #
# ----------------------------------------------------- #

import os
import pandas as pd
from snakemake.utils import validate
from snakemake.utils import min_version

__author__ = "Dr. Rina Ahmed-Begrich"

bold = "\033[1m"
green = "\033[92m"
cyan = "\033[36m"
end = "\033[0m"

msg = f"""{cyan}\nONT-basecalling: A Snakemake workflow
for nanopore basecalling and demultiplexing using dorado.{end}"""

epilog = f"""
{cyan}Written by {__author__}.
Max Planck Unit for the Science of Pathogens. Copyright (c) 2025.{end}

"""
# -----------------------------------------------------
# check minimum snakemake version
# -----------------------------------------------------
min_version("8.24.1")


# -----------------------------------------------------
# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# -----------------------------------------------------
# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/basecall.smk"


# -----------------------------------------------------
# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Dorado bascalling workflow started ---\n")
    print(f"Current working directory: {os.getcwd()}")
    print(f"Output directory: {os.getcwd()}/results")
    print()


onsuccess:
    print()
    print(msg)
    print(epilog)
    print("--- Workflow finished! ---")
    print()


onerror:
    print()
    print(msg)
    print(epilog)
    print("--- An error occurred! ---")
    print()


# -----------------------------------------------------
# target rules
# -----------------------------------------------------
rule all:
    input:
        expand(
            "results/{run}/dorado_final/input_fastq.txt",
            run=runs.index,
        ),
    default_target: True
