# ----------------------------------------------------- #
# A Snakemake workflow for nanopore basecalling         #
# and multiplexing using dorado.                        #
# ----------------------------------------------------- #

import os
import pandas as pd
from snakemake.utils import validate
from snakemake.utils import min_version


# -----------------------------------------------------
# meta data and run info
# -----------------------------------------------------
__authors__ = ["Rina Ahmed-Begrich", "Michael Jahn"]

cyan = "\033[36m"
end = "\033[0m"

msg = f"""\nONT-basecalling: A Snakemake workflow
for nanopore basecalling and demultiplexing using dorado."""

prolog = f"Output directory: {os.getcwd()}/results"

epilog = f"""
Written by {", ".join(__authors__)}.
Max Planck Unit for the Science of Pathogens. Copyright (c) 2025.
"""

# -----------------------------------------------------
# check minimum snakemake version
# -----------------------------------------------------
min_version("8.24.1")


# -----------------------------------------------------
# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# -----------------------------------------------------
# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/basecall.smk"


# -----------------------------------------------------
# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print(f"{cyan}\n--- Workflow started! ---\n\n{prolog}\n\n{end}")


onsuccess:
    print(f"{cyan}\n{msg}\n{epilog}\n--- Workflow finished! ---\n\n{end}")


onerror:
    print(f"{cyan}\n{msg}\n{epilog}\n --- An error occurred! ---\n\n{end}")


# -----------------------------------------------------
# target rules
# -----------------------------------------------------
rule all:
    input:
        expand(
            "results/{run}/dorado_final/input_fastq.txt",
            run=runs.index,
        ),
    default_target: True
