default-resources:
  # slurm_account: "<account>"
  slurm_partition: "gpu"
  mem_mb_per_cpu: 1800 # take a sensible default for your cluster
  runtime: "1h"
  tmpdir: 10000 # 10 GB

# here only rules, which require different (more) resources:
set-resources:
  dorado_simplex:
    mem_mb_per_cpu: 4000 # 4 GB
    runtime: "24h" # 24 hours
    gpu: 1
  generate_barcodes:
    mem_mb_per_cpu: 4000 # 4 GB
    runtime: "4h" # 24 hours

# parallelization with threads needs to be defined separately:
set-threads:
  dorado_simplex: 1
  dorado_demux: 20
  merge_and_bgzip_fastqs: 20
