input:
  runs: "config/runs.csv"
  file_pattern: "*.pod5"

output:
  results: "results"
  logs: "results/logs"

dorado:
  path: "path/to/dorado"
  simplex:
    cuda: auto #cuda:all
    trim: "none" #"all"
