jobs: 4
local-cores: 4

default-resources:
  runtime: "1h"
  cpus_per_task: 1
  cpus: 1

# rules, which require different (more) resources:
set-resources:
  dorado_demux:
    cpus_per_task: 1
    cpus: 2

# parallelization with threads needs to be defined separately:
set-threads:
  dorado_simplex: 1
  dorado_demux: 2
  merge_and_bgzip_fastqs: 1
